[tox]
isolated_build = true
envlist = py{39,310,311,312}, pylint, mypy, black

[testenv]
setenv =
    PYTHONPATH = {toxinidir}
deps =
    pydantic=={env:PYDANTIC_VERSION}
    httpx=={env:HTTPX_VERSION}
    pyright
    click
allowlist_externals = poetry
commands_pre =
    poetry install
commands =
    poetry run pytest --tb=short tests/
    pyright foundry/
passenv = PYDANTIC_VERSION,HTTPX_VERSION

[testenv:black]
deps =
    black == 24.1.1
commands =
    black --check foundry tests
