[tox]
isolated_build = true
envlist = py{39,310,311,312}, pylint, mypy, black

[testenv]
setenv =
    PYTHONPATH = {toxinidir}
deps =
    pydantic=={env:PYDANTIC_VERSION}
    httpx=={env:HTTPX_VERSION}
allowlist_externals = poetry
commands_pre =
    poetry install
commands =
    poetry run pytest --tb=short tests/
passenv = PYDANTIC_VERSION,HTTPX_VERSION

[testenv:pyright]
deps =
    pyright
    click
commands =
    pyright foundry/

[testenv:black]
deps =
    black == 24.1.1
commands =
    black --check foundry tests
