#  Copyright 2024 Palantir Technologies, Inc.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

"""
    Palantir OpenAPI

    The Palantir REST API. Please see https://www.palantir.com/docs for more details.

    The version of the OpenAPI document: 1.738.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# The SDK version
from foundry.versions import __version__

# The OpenAPI document version from the spec information
# See https://swagger.io/specification/#info-object
from foundry.versions import __openapi_document_version__

# The OpenAPI specification version
# See https://swagger.io/specification/#versions
from foundry.versions import __openapi_specification_version__

# The version of the generator used to generate the SDK
from foundry.versions import __openapi_generator_version__


# import ApiClient
from foundry.api_response import ApiResponse
from foundry.auth.foundry_oauth_client import ConfidentialClientAuth
from foundry.auth.foundry_auth_token_client import UserTokenAuth
from foundry.configuration import Configuration
from foundry.exceptions import OpenApiException
from foundry.exceptions import ApiValueError
from foundry.exceptions import ApiKeyError
from foundry.exceptions import ApiAttributeError
from foundry.exceptions import ApiException
from foundry.foundry_client import FoundryClient
